### ISSUE TITLE
A problem occured when I run ./experiments/scripts/FP_Net_end2end.sh

### ISSUE THREAD

**Issue by junjieAI** [unsky/FPN-caffe#14]
Hi unsky:
when I run ./experiments/scripts/FP_Net_end2end.sh, I got a problem as follow:
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 43, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/roi_data_layer/layer.py", line 125, in setup
    top[idx].reshape(1, self._num_classes * 4)
IndexError: Index out of range
And the pretrained_model I used is VGG16.v2.caffemodel, hope you can give me some help, Thanks

**Comment by junjieAI** [comment]
@unsky I solved the error by changing "__C.TRAIN.HAS_RPN = False" to True, but another error occured , asfollow: 

I1117 15:04:06.969494 17203 net.cpp:270] This network produces output rpn_loss_bbox/p5
I1117 15:04:06.969593 17203 net.cpp:283] Network initialization done.
I1117 15:04:06.969837 17203 solver.cpp:60] Solver scaffolding done.
Solving...
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/roi_data_layer/layer.py", line 144, in forward
    blobs = self._get_next_minibatch()
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/roi_data_layer/layer.py", line 63, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/roi_data_layer/minibatch.py", line 34, in get_minibatch
    assert len(im_scales) == 1, "Single batch only"
AssertionError: Single batch only

**Comment by unsky** [comment]
i have update codes
