### ISSUE TITLE
This model can not support LMDB train data?

### ISSUE THREAD

**Issue by pengyulong** [unsky/FPN-caffe#5]
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 62, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/t91/pengyulong/workspace/FPN/tools/../lib/datasets/factory.py", line 37, in get_imdb
    raise KeyError('Unknown dataset: {}'.format(name))
KeyError: 'Unknown dataset: /home/t91/data/lmdb/train_lmdb'

**Comment by unsky** [comment]
The code is based on py-faster rcnn。image iter only.
