### ISSUE TITLE
make -j16 all出错

### ISSUE THREAD

**Issue by yin19961202** [unsky/FPN-caffe#70]
请问有人在make -j16 all时出现下面的问题吗？
tools/CMakeFiles/upgrade_net_proto_text.dir/build.make:134: recipe for target 'tools/upgrade_net_proto_text' failed
make[2]: *** [tools/upgrade_net_proto_text] Error 1
CMakeFiles/Makefile2:739: recipe for target 'tools/CMakeFiles/upgrade_net_proto_text.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_text.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xubo00** [comment]
估计是版本的问题,老版的caffe的include以及src下的layer目录下的一些相关文件需要替换.你可以查一下,尝试一下.

**Comment by basaltzhang** [comment]
if you not familar with cmake, just config the Makefile.config file by yourself. That maybe more controllable.

**Comment by yin19961202** [comment]
I don’t know how to config the Makefile.config. Can you tell me?Thanks very much!


| |
尹锐红
邮箱：13261061903@163.com
|

签名由 网易邮箱大师 定制

在2018年06月08日 10:34，Zhang Yifeng 写道：

if you not familar with cmake, just config the Makefile.config file by yourself. That maybe more controllable.

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2

**Comment by qianfangjj** [comment]
> I don’t know how to config the Makefile.config. Can you tell me?Thanks very much! | | 尹锐红 邮箱：13261061903@163.com | 签名由 网易邮箱大师 定制 在2018年06月08日 10:34，Zhang Yifeng 写道： if you not familar with cmake, just config the Makefile.config file by yourself. That maybe more controllable. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你好，请问你的这个问题解决了吗？我遇到了同样的问题，可不可以跟我说一下你的解决方法？

**Comment by unsky** [comment]
使用cmake按照readme编译
