### ISSUE TITLE
make -j16 all  BUG.....

### ISSUE THREAD

**Issue by jiachen0212** [unsky/FPN-caffe#71]
../lib/libcaffe.so.1.0.0-rc3：对‘cv::String::allocate(unsigned long)’未定义的引用
../lib/libcaffe.so.1.0.0-rc3：对‘cv::imread(cv::String const&, int)’未定义的引用
../lib/libcaffe.so.1.0.0-rc3：对‘cv::String::deallocate()’未定义的引用
../lib/libcaffe.so.1.0.0-rc3：对‘cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)’未定义的引用
collect2: error: ld returned 1 exit status
examples/CMakeFiles/convert_mnist_data.dir/build.make:133: recipe for target 'examples/mnist/convert_mnist_data' failed
make[2]: *** [examples/mnist/convert_mnist_data] Error 1

maybe the opencv bug?  I tried a lot of ways but still didn't solve the problem...
anyone can give some help?  thanks!

**Comment by xubo00** [comment]
可以尝试在lib目录下,make一下,这个问题看起来全是在lib目录下出现的.或者重新下载FPN-master,重新编译y一下caffe-fpn,另外就是也可以检查一下opencv等等安装的是否正确.希望对你有用.

**Comment by jiachen0212** [comment]
谢谢啊～

**Comment by basaltzhang** [comment]
If you are using opencv3, please make sure this place should **not** be commented: https://github.com/unsky/FPN/blob/master/caffe-fpn/Makefile.config#L21

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2
