### ISSUE TITLE
训练好的caffemodel容量1.2G

### ISSUE THREAD

**Issue by SineXue** [unsky/FPN-caffe#79]
得到的结果也没什么问题就是训练好的caffemodel很大，不明白为什么，求大神解答

**Comment by unsky** [comment]
FPN里面并没有太考虑模型的参数量，有大量的可优化空间，但不属于该论文的讨论范畴

**Comment by SineXue** [comment]
多谢解答，还有我想请问这个如果在fddb上面测试的话，修改tools/demo.py的一些内容可以正常进行吗，因为我在测试过程中遇到一些问题，麻烦你了

**Comment by SineXue** [comment]
已经解决了，多谢

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2
