### ISSUE TITLE
scale problem

### ISSUE THREAD

**Issue by SineXue** [unsky/FPN-caffe#81]
大神，我看到FPN中的scales=2 ** np.arange(4, 6)，但是论文里面不是说每一层anchor都是单一尺度吗,还是我理解错了，这样怎么生成[32,64,128,256,512]的呢

**Comment by unsky** [comment]
readme有解释

**Comment by SineXue** [comment]
看到了，多谢解答！

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2
