### ISSUE TITLE
Does the code support training fpn with batch size 1 with one gpu? 

### ISSUE THREAD

**Issue by anorthman** [unsky/FPN-caffe#83]
Does the code support training fpn with batch size 1 with one gpu?

**Comment by unsky** [comment]
yes

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2

**Comment by anorthman** [comment]
> yes

ths

**Comment by anorthman** [comment]
@unsky ok

**Comment by anorthman** [comment]
@mantou22 no layer named "rpn_rois/p2"

**Comment by mantou22** [comment]
@anorthman   there is this layer named  “rpn_rois/p2”

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN_1/tools/demo.py", line 144, in 
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN_1/tools/../lib/fast_rcnn/test.py", line 298, in im_detect
box_deltas = box_deltas * stds + means
ValueError: operands could not be broadcast together with shapes (1000,8) (84,)

**Comment by mantou22** [comment]
作者您好.
训练集为100*100左右图片， 目标大小为40*40左右，请问如何设置anchor的大小

**Comment by unsky** [comment]
可以参考yolo对数据集进行分析 进行聚类

**Comment by mantou22** [comment]
您好，请问为什么我训练自己的模型会怎么慢速度？
前面几百次迭代，每20次只需要 34S 左右， 到了2000次左右时， 每20次需要 5-6分钟 为什么会那么慢？？？？？  我的显卡是 GPU 1080Ti 的  12G运行内存
