### ISSUE TITLE
when I run demo.py. i met a problem, shapes (1000,8) (84,) 

### ISSUE THREAD

**Issue by mantou22** [unsky/FPN-caffe#87]
Traceback (most recent call last):
  File "/home/xmpu234/Documents/FPN_1/tools/demo.py", line 144, in <module>
    _, _= im_detect(net, im)
  File "/home/xmpu234/Documents/FPN_1/tools/../lib/fast_rcnn/test.py", line 298, in im_detect
    box_deltas = box_deltas * stds + means
ValueError: operands could not be broadcast together with shapes (1000,8) (84,)

**Comment by shabalabalabala** [comment]
打开lib>>fast-rcnn>>test.py
       将num_classes = 21（line 215）更改为num_classes = 2
以及修改prototxt中相应的类别
